version: '3.8'

services:
  mistral:
    build:
      context: ./mistral
      dockerfile: Dockerfile
    volumes:
      - ./mistral:/app  # If you have any local inference scripts

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mistral
